# Example config



### General

# Log level. Currently only supports debug. Any other value will result in info level.
log_level: debug



### Database
db:
    # Path to database dir
    path: travel-token-matrix-app-service-db



### Matrix
matrix:
    # Homeserver access token, must be the same as the one used in the matrix server config
    access_token: ugw8243igya57aaABGFfgeyu

    # Port for serving HTTP. Matrix server will send requests to this port.
    http_port: 9090
